import os
import json
import csv
import zipfile
from datetime import datetime
from tts_tamil import generate_tamil_speech


OUTPUT_DIR = "output"
ZIP_FILENAME = "output_bundle.zip"


def generate_text_report():
    filepath = os.path.join(OUTPUT_DIR, "report.txt")
    with open(filepath, "w") as f:
        f.write("=== POC Output Report ===\n")
        f.write(f"Generated at: {datetime.now().isoformat()}\n")
        f.write(f"Machine: Google Colab\n")
        f.write("\nThis file was auto-generated by the Colab POC pipeline.\n")
    return filepath


def generate_json_data():
    filepath = os.path.join(OUTPUT_DIR, "data.json")
    data = {
        "project": "colab_poc",
        "timestamp": datetime.now().isoformat(),
        "results": [
            {"id": i, "value": i * 3.14, "status": "ok"}
            for i in range(1, 11)
        ],
    }
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2)
    return filepath


def generate_csv_data():
    filepath = os.path.join(OUTPUT_DIR, "metrics.csv")
    with open(filepath, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "metric_name", "value", "unit"])
        metrics = [
            (1, "cpu_usage", 45.2, "%"),
            (2, "memory_usage", 62.8, "%"),
            (3, "disk_io", 120.5, "MB/s"),
            (4, "network_latency", 12.3, "ms"),
            (5, "throughput", 9500, "req/s"),
        ]
        writer.writerows(metrics)
    return filepath


def create_zip(files):
    with zipfile.ZipFile(ZIP_FILENAME, "w", zipfile.ZIP_DEFLATED) as zf:
        for filepath in files:
            zf.write(filepath, os.path.basename(filepath))
    return ZIP_FILENAME


def run():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("Generating output files...")
    files = [
        generate_text_report(),
        generate_json_data(),
        generate_csv_data(),
    ]

    print("\nGenerating Tamil speech...")
    tamil_texts = [
        ("வணக்கம், நீங்கள் எப்படி இருக்கிறீர்கள்?", "greeting.wav"),
        ("இன்று வானிலை மிகவும் அழகாக இருக்கிறது.", "weather.wav"),
        ("நன்றி, மீண்டும் சந்திப்போம்.", "farewell.wav"),
    ]
    for text, filename in tamil_texts:
        path = generate_tamil_speech(text, filename)
        files.append(path)

    for f in files:
        print(f"  Created: {f}")

    print("Creating zip bundle...")
    zip_path = create_zip(files)
    zip_size = os.path.getsize(zip_path)
    print(f"  Zip created: {zip_path} ({zip_size} bytes)")

    return zip_path


if __name__ == "__main__":
    run()
